# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LendPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default='unnamed object', max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='lending date')),
                ('person', models.CharField(default='anonymous person', max_length=200)),
                ('ifreturned', models.BooleanField(default=0)),
                ('return_date', models.DateTimeField(verbose_name='return date')),
            ],
        ),
    ]
