# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lendlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendpost',
            name='lendOrPost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lendpost',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
