# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giventakelist', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LendPost',
            new_name='ListPost',
        ),
    ]
