# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 17:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giventakelist', '0002_auto_20160804_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpost',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 22, 42, 46, 769000), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='listpost',
            name='return_date',
            field=models.DateTimeField(blank=True, verbose_name='return date'),
        ),
    ]
