# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('giventakelist', '0003_auto_20160804_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpost',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
        ),
    ]
