# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giventakelist', '0004_auto_20160804_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpost',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='return date'),
        ),
    ]
