# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giventakelist', '0005_auto_20160804_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listpost',
            old_name='lendOrPost',
            new_name='lendOrBorrow',
        ),
    ]
