# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giventakelist', '0006_auto_20160805_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listpost',
            options={'ordering': ('ifreturned', 'pub_date')},
        ),
    ]
